import type { RestrictedCommenter, WorkComment } from "@/types/comment";

/** 데모용 작품 댓글 — 크리에이터스: 작품·회차 단위 통합 조회 */
export const MOCK_WORK_COMMENTS: WorkComment[] = [
  {
    id: "c1",
    seriesId: "1",
    seriesTitle: "꽃에게는 독이 필요하다",
    episodeLabel: "120화",
    authorName: "novel_lover",
    content: "다음 회가 너무 기대돼요! 황녀 장면 특히 좋았습니다.",
    createdAt: "5분 전",
    likeCount: 24,
    replyCount: 1,
    isPicked: true,
    isCreator: false,
  },
  {
    id: "c2",
    seriesId: "1",
    seriesTitle: "꽃에게는 독이 필요하다",
    episodeLabel: "120화",
    authorName: "사자이빨닦기",
    content: "읽어 주셔서 감사합니다. 다음 화도 곧 올려요.",
    createdAt: "12분 전",
    likeCount: 86,
    replyCount: 0,
    isPicked: false,
    isCreator: true,
  },
  {
    id: "c3",
    seriesId: "1",
    seriesTitle: "꽃에게는 독이 필요하다",
    episodeLabel: "119화",
    authorName: "moonreader",
    content: "복선이 하나씩 풀리는 맛이 있어요. 독 설정이 참신합니다.",
    createdAt: "어제",
    likeCount: 41,
    replyCount: 0,
    isPicked: true,
    isCreator: false,
  },
  {
    id: "c4",
    seriesId: "2",
    seriesTitle: "달빛 아래 그대",
    episodeLabel: "50화",
    authorName: "soft_night",
    content: "재회 장면 울컥했어요. 대사 한 줄이 오래 남습니다.",
    createdAt: "어제",
    likeCount: 18,
    replyCount: 2,
    isPicked: false,
    isCreator: false,
  },
  {
    id: "c5",
    seriesId: "1",
    seriesTitle: "꽃에게는 독이 필요하다",
    episodeLabel: "118화",
    authorName: "critic99",
    content: "전개가 느린 것 같아요. 조금 더 템포 올려주시면 좋겠어요.",
    createdAt: "2025.12.20",
    likeCount: 3,
    replyCount: 0,
    isPicked: false,
    isCreator: false,
  },
  {
    id: "c6",
    seriesId: "2",
    seriesTitle: "달빛 아래 그대",
    episodeLabel: "48화",
    authorName: "bookworm",
    content: "배경 묘사가 예뻐요. 서울 밤 공기가 느껴집니다.",
    createdAt: "2025.12.18",
    likeCount: 12,
    replyCount: 1,
    isPicked: false,
    isCreator: false,
  },
  {
    id: "c7",
    seriesId: "1",
    seriesTitle: "꽃에게는 독이 필요하다",
    episodeLabel: "117화",
    authorName: "fanclub_a",
    content: "이번 화 반전 미쳤다… 다시 처음부터 읽고 있어요.",
    createdAt: "2025.12.15",
    likeCount: 67,
    replyCount: 3,
    isPicked: true,
    isCreator: false,
  },
  {
    id: "c8",
    seriesId: "1",
    seriesTitle: "꽃에게는 독이 필요하다",
    episodeLabel: "116화",
    authorName: "quiet_room",
    content: "캐릭터 대사가 너무 길어요. 요약이 필요할 듯.",
    createdAt: "2025.12.10",
    likeCount: 1,
    replyCount: 0,
    isPicked: false,
    isCreator: false,
  },
];

/** 데모용 댓글 작성 제한 이용자 — 크리에이터스: 제한 이용자 관리 */
export const MOCK_RESTRICTED_COMMENTERS: RestrictedCommenter[] = [
  {
    id: "r1",
    authorName: "spam_user01",
    restrictedAt: "2025.12.01",
    reason: "반복 도배·비방",
    seriesTitle: "꽃에게는 독이 필요하다",
  },
  {
    id: "r2",
    authorName: "troll_night",
    restrictedAt: "2025.11.20",
    reason: "욕설·혐오 표현",
    seriesTitle: "달빛 아래 그대",
  },
];
