import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MobileViewportSync } from "@/components/MobileViewportSync";
import { Toaster } from "@/components/ui/toaster";
import DevConsoleFilter from "@/components/DevConsoleFilter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  /** 키보드가 visual viewport만 줄여 화면이 눌리는 동작 완화 (Chrome 등) */
  interactiveWidget: "resizes-content",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-dvh overflow-hidden overscroll-none">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 flex h-dvh w-full flex-col overflow-hidden overscroll-none p-0`}
      >
        <DevConsoleFilter />
        <MobileViewportSync />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
