import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full min-h-screen">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 flex min-h-screen w-full flex-col p-0`}
        style={{ minHeight: "100vh", height: "100%", width: "100%" }}
      >
        {children}
      </body>
    </html>
  );
}
